package com.tici.vpn.proxy.master.settings.adsblock

/**
 * Renders Privoxy's `default.action` from rule domains. Pure (no Android deps).
 *
 * Gate 2: every domain is re-validated regardless of where it came from (DB rows may predate a
 * validator fix); invalid ones are dropped, never escaped. Each rule is emitted as `.domain`, the
 * only form Privoxy matches as "domain and all subdomains". The block reason is a fixed literal —
 * user text never appears inside `{}`.
 */
object ActionFileGenerator {

    data class RenderResult(val text: String, val droppedCount: Int)

    const val HEADER = "# Generated by SuperVPN. Do not edit — regenerated on every connect.\n" +
        "{+block{Ad or tracker domain.} +handle-as-image}\n"

    fun render(domains: List<String>): RenderResult {
        var dropped = 0
        val valid = LinkedHashSet<String>()
        for (d in domains) {
            when (val r = DomainValidator.validate(d)) {
                is DomainValidator.Result.Valid -> valid.add(r.domain)
                is DomainValidator.Result.Invalid -> dropped++
            }
        }
        if (valid.isEmpty()) return RenderResult("", dropped)
        val text = buildString {
            append(HEADER)
            valid.forEach { append('.').append(it).append('\n') }
        }
        return RenderResult(text, dropped)
    }
}
