package com.tici.vpn.proxy.master.settings.adsblock

/**
 * Renders the engine's blocklist file (engine/blocklist.go `AddRule`) from rule rows.
 * Pure (no Android deps).
 *
 * Every rule is re-validated regardless of where it came from (DB rows may predate a validator
 * fix); invalid ones are dropped, never escaped. One rule per line: `domain` blocks it and all
 * subdomains, `domain/path` blocks that path prefix via selective MITM.
 */
object BlocklistGenerator {

    data class RenderResult(val text: String, val droppedCount: Int)

    const val HEADER = "# Generated by SuperVPN. Do not edit — regenerated on every change.\n"

    fun render(rules: List<String>): RenderResult {
        var dropped = 0
        val valid = LinkedHashSet<String>()
        for (r in rules) {
            when (val v = DomainValidator.validate(r)) {
                is DomainValidator.Result.Valid -> valid.add(v.domain)
                is DomainValidator.Result.Invalid -> dropped++
            }
        }
        if (valid.isEmpty()) return RenderResult("", dropped)
        val text = buildString {
            append(HEADER)
            valid.forEach { append(it).append('\n') }
        }
        return RenderResult(text, dropped)
    }
}
