package com.highsecure.vpn.proxy.master.remoteconfig

object AdPlacementId {

    const val INTER_ART_HOME = "INTER_ART_HOME"
    const val INTER_ART_TRENDING = "INTER_ART_TRENDING"
    const val INTER_ART_INCOMPLETE = "INTER_ART_INCOMPLETE"
    const val INTER_ART_COMPLETED = "INTER_ART_COMPLETED"
    const val INTER_ART_CREATOR_LIST = "INTER_ART_CREATOR_LIST"
    const val INTER_ART_CREATOR_CAMERA = "INTER_ART_CREATOR_CAMERA"
    const val INTER_ART_CREATOR_GALLERY = "INTER_ART_CREATOR_GALLERY"
    const val INTER_ART_PAINTING_60_PERCENT_COMPLETED = "INTER_ART_PAINTING_60_PERCENT_COMPLETED"
    const val INTER_ART_PAINTED = "INTER_ART_PAINTED"

    const val NATIVE_LANGUAGE = "NATIVE_LANGUAGE"
    const val NATIVE_REWARDED = "NATIVE_REWARDED"
    const val NATIVE_PAINTED = "NATIVE_PAINTED"

    const val REWARD_FUNCTION_EDIT = "REWARD_FUNCTION_EDIT"
    const val REWARD_ART_HOME = "REWARD_ART_HOME"
    const val REWARD_ART_DETAIL_CATEGORY = "REWARD_ART_DETAIL_CATEGORY"

    const val OPEN_RESUME = "OPEN_RESUME"
    const val OPEN_SPLASH = "OPEN_SPLASH"

    const val BANNER_HOME= "BANNER_HOME"
    const val BANNER_CAMERA= "BANNER_CAMERA"
    const val BANNER_PAINTING= "BANNER_PAINTING"
    const val BANNER_PAINTED= "BANNER_PAINTED"
}